### ISSUE TITLE
`\` not supported

### ISSUE THREAD

**Issue by mariari** [heliaxdev/minijuvix#195] opened 2022-06-24 16:12 UTC
Although `\` is reserved for lambda, it should be free for other names

```haskell
   |
23 | axiom +\\\ : Bool → Bool;
   |        ^
unexpected '\'
expecting ':'
```

**Comment by janmasrovira** [comment] 2022-06-28 12:13
The problem is that when we find 
```
x\
```
we don't know if `x` is an identifier followed by a lambda or the `x\` identifier.
The only option that occurs to me now is to try to desambiguate that with `try` statements. However, I don't think the tradeoff is worth it. Do you have another solution in mind?

**Comment by janmasrovira** [comment] 2022-07-01 14:05
closing this

**Closed by janmasrovira** 2022-07-01 14:05 UTC
